docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-vi.tfvars, examples/vsphere/sample-terraform.tfvars, main.tf, roles/kubernetes/loadbalancer/kube_vip/primary/tasks/main.yaml, templates/ansible/ansible-vars.yaml.tmpl, variables.tf
kube-vip configuration no longer requires an interface assignment. Enabled new kube-vip loadBalancer.
=> (IAC-592) kube-vip updates

roles/kubernetes/common/tasks/main.yaml
Currently the project simply replaces the entire GRUB_CMDLINE_LINUX line, regardless of whether the user already has options set here. It should instead only add the needed option to the existing line.
I imagine this could all be done with a single regex if one wanted to take the time to devise one, but the solutions I found online were impossible to understand and didn't work as advertised. The added code can be understood relatively easily and should cover most cases. Tested with:
1. GRUB_CMDLINE_LINUX not in file at all. Added as: 
`GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1"`
2. GRUB_CMDLINE_LINUX in file but an empty string. Updated to:
`GRUB_CMDLINE_LINUX=" systemd.unified_cgroup_hierarchy=1"`
3. Option present but contains unrelated setting "foo". Updated to: …
=> (IAC-605) Don't replace GRUB_CMDLINE_LINUX if it already exists

docs/REQUIREMENTS.md, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-vi.tfvars, main.tf, modules/vm/main.tf, modules/vm/variables.tf, playbooks/kubernetes-install.yaml, roles/kubernetes/control_plane/init/primary/templates/kubeadm-config.j2, roles/kubernetes/node/baseline/tasks/main.yaml, roles/kubernetes/node/labels_taints/roles/tasks/main.yaml, roles/kubernetes/node/labels_taints/system/tasks/main.yaml, roles/kubernetes/node/labels_taints/tasks/labels.yaml, roles/kubernetes/node/labels_taints/tasks/taints.yaml, roles/kubernetes/node/removal/tasks/main.yaml, roles/kubernetes/storage/sig-storage-local-static-provisioner/defaults/main.yaml, roles/kubernetes/storage/sig-storage-local-static-provisioner/tasks/main.yaml, roles/systems/vsphere/init/files/create_partitions.sh, roles/systems/vsphere/init/files/link_devs.sh, roles/systems/vsphere/init/tasks/main.yaml, templates/ansible/ansible-vars.yaml.tmpl, templates/ansible/inventory.tmpl, variables.tf
Add in code to add n number of misc disks to a vm when identified in the node_pools configuration. Also added in the skeleton for the container registry VM.
=> (IAC-594) node_pools items can now add in n number of misc disks

templates/ansible/ansible-vars.yaml.tmpl, templates/ansible/inventory.tmpl
Fixes logic in the ansible template files for the cr, jump, and nfs vms, so if the user opts to not create one of those resources it no longer throws an error.
Set the create flags for all the external servers to true, I also opted to use static ips for these resources 
```
create_jump = true
create_nfs = true
create_cr = true
```
Resources were successfully created, both the inventory and ansible-vars.yaml template successfully rendered and saved to disk WITH the jump, nfs, and cr sections
Set the create flags for all the external servers to false
```
create_jump = false
create_nfs = false
create_cr = false
```
Resources were not created as expected, and both the inventory and ansible-vars.yaml template successfully rendered and saved to disk WITHOUT the jump, nfs, and cr sections
Ensure …
=> fix: (IAC-621) Update Ansible template files

docs/CONFIG-VARS.md, roles/systems/postgres/tasks/main.yaml
Updating the SSL cert/key naming scheme that is used if you set `server_ssl` to on, and you do not define either `server_ssl_cert_file` or `server_ssl_cert_file`. The files will now have the format `ssl-cert-sas-${PG_HOST}.pem` and `ssl-cert-sas-${PG_HOST}.key`. The cert/key file should no longer be overwritten when mutliple postgres hosts are created using this configuration.
Additional details in internal ticket, test summary:
1. Created a .tfvars that included 2 postgres servers (named default & extra) both with `server_ssl` on and `server_ssl_cert_file` or `server_ssl_cert_file` not set
2. Ran "apply setup install"
3. Infrastructure was successfully created
4. Both PG VMs had postgres installed and correctly configured with ssl on and both the cert & key set
5. On the PG VMs the cert …
=> fix: (IAC-578) Update SSL Cert/Key Naming Scheme

docs/CONFIG-VARS.md
Updated the link in the `cluster_version` cell to point to the SAS Viya Kubernetes version requirements information. This will make it clear which versions are supported in the context of Viya 4.
Verified the link is formatted correctly and leads to the correct page/section
=> docs: (IAC-656) Update Supported Kubernetes Versions Link

docs/REQUIREMENTS.md, examples/bare-metal/sample-ansible-vars.yaml, playbooks/kubernetes-install.yaml, roles/kubernetes/loadbalancer/kube_vip/cloud_provider/templates/kube-vip-cm.tmpl, templates/ansible/ansible-vars.yaml.tmpl
`https://kube-vip.chipzoller.dev` should now be `https://kube-vip.io`
Verified the updated URLs lead to the correct page & section
=> docs: (IAC-671) Update kube-vip URL

roles/kubernetes/cni/calico/tasks/main.yaml
New cluster creations are failing while installing the calico operator. Error is:
`"stderr": "The CustomResourceDefinition \"installations.operator.tigera.io\" is invalid: metadata.annotations: Too long: must have at most 262144 bytes"`
I don't know why I've just started seeing this; perhaps the CRD size has grown. 
The [calico docs](https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico-with-kubernetes-api-datastore-50-nodes-or-less) indicate that 'kubectl create' should be used instead of 'kubectl apply'. The former avoids the creation of the 'last-applied-configuration' annotation, which is likely the problem here. I confirmed in my own environment that using 'kubectl create' yields a successfully created cluster.
=> feat: (IAC-678) Use 'kubectl create' rather than 'kubectl apply' when creating calico resources

Dockerfile, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-vi.tfvars, variables.tf
Update default K8s version to 1.23.8, this is order to be within the +/- range of K8s 1.24.
| Scenario | K8s Version | Order  | Cadence   | Deployment Success |
| -------- | ----------- | ------ | --------- | ------------------ |
| 1        | 1.24.3      | *| fast:2020 | yes                |
| 2        | 1.22.12     | *| fast:2020 | yes                |
=> feat: (IAC-657) Update default K8s version to 1.23.8

roles/kubernetes/sas-iac-buildinfo/tasks/main.yaml
Added logic that keeps the sas-iac-buildinfo configMap from being created on bare-metal machines.
=> sas-iac-buildinfo does not run on bare-metal

docs/CONFIG-VARS.md, docs/REQUIREMENTS.md
Updating the SAS Viya name in the documentation
The repo's "About" section will also need to change as part of this PR, since that's not controlled by the code I'll put the updated content here. Please review this as well.
>This project contains Terraform scripts to provision cloud infrastructure resources, when using vSphere, and Ansible to apply the needed elements of a Kubernetes cluster that are required to deploy SAS Viya platform product offerings.
=> docs: (IAC-864) Update SAS Viya name in documentation

Dockerfile, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, variables.tf
Since the SAS Viya Platform will be supporting K8s 1.23, 1.24, and 1.25 in March as part of the 2023.03 cadence, the kubectl and cluster_version version is being changed to 1.24.10 so that it's within the +/- 1 range of the supported versions. 
| Scenario | Task | Provider | Order  | Cadence        | cluster_version | Orchestration       | Deployment Method	 Version | kubectl Version | INGRESS_NGINX_CHART_VERSION |
|:---------|:-----|:---------|:-------|:---------------|:----------------|:--------------------|:---------------------------|:----------------|:----------------------------|
| 1        | OOTB | vmware   | *| stable:2023.01 | 1.24.10         | Deployment Operator | Docker                     | 1.24.10         | 4.3.0                       |
| 2        | OOTB | vmware   | *| …
=> feat: (IAC-902) Update default K8s version to 1.24.10

examples/bare-metal/sample-inventory-internal-postgres
Created a sample inventory file at `examples/bare-metal/sample-inventory-internal-postgres` that users can use if they do not want to configured a machine to be an external postgres instance.
Provisioned some instances in vcenter and ran through a "setup install" after filling out an inventory file that did not have the postgres hostgroups defined. I saw that the postgres tasks were correctly skipped and did not result in an error. Afterwards I used viya4-deployment to perform a deployment that has an internal postgres configured.
* Provider: oss
* K8s Version: v1.25.6
* Order: *
* Cadence: fast:2020
* Postgres: internal
* Orchestration: deployment operator
See internal ticket for more details
=> docs: (IAC-716) provide inventory sample without postgres host groups

Dockerfile, README.md, docs/REQUIREMENTS.md, versions.tf
Updated the default and minimum required Terraform version to 1.4.5, to pull in the latest features, fixes, and security patches from HashiCorp.
Consumers of the Dockerfile will already have the version updated within the installation stages. For users that are running viya4-iac-k8s directly on their machine without the use of the Docker container (by executing the `oss-k8s.sh` or `terraform`)should update their terraform version to at least 1.4.5.
Users who have previously created OSS infrastructure with viya4-iac-k8s releases 2.3.0 or earlier should still be able to manage their infrastructure after updating the terraform version to 1.4.5.
| Scenario | Provider | kubernetes_version | kubectl version | Deployment Method | Terraform Version | Order  | Cadence   | Notes …
=> feat!: (IAC-971) Update Terraform Version to 1.4.5

roles/kubernetes/toolbox/tasks/main.yaml
Adds `trusted=yes` to the kubernetes-xenial APT repo entry in `/etc/apt/sources.list.d/kubernetes.list` to get around this open Kubernetes issue https://github.com/kubernetes/release/issues/2862
After the changes went in recreated my infrastructure in vsphere and ran setup, install. I verified that I no longer ran into the failure during the `kubernetes/toolbox : Update apt package index and install kubelet, kubeadm, kubectl` task and I was able to use kubectl to check my cluster.
| Scenario | Provider | Type     | kubernetes_version | kubectl version | Deployment Method | OS           | Notes                               |
|----------|----------|----------|--------------------|-----------------|-------------------|--------------|-------------------------------------| 
| 1        | OSS …
=> fix: (IAC-1042) Fix kubernetes-xenial APT Repo Public Key Error

docs/CONFIG-VARS.md, examples/bare-metal/sample-inventory
Update the sample inventory file that we provide for bare metal.
`postgres_ip` is not a valid field and instead should be replaced with `postgres_server_name`
| Scenario | Provider | Type       | kubernetes_version | kubectl version | Deployment Method | Terraform Version |
|----------|----------|------------|--------------------|-----------------|-------------------|-------------------| 
| 1        | OSS      | bare metal | 1.25.8             | 1.25.8          | Docker            | v1.4.5
=> fix: (IAC-1027) Sample Inventory file for bare metal is incorrect

Dockerfile
- Use apt-get tool versus apt per hadolint warning
- Add apt-get clean and apt/lists/* removal for each use of apt-get update
See internal ticket for command output details and terraform.tfvars file.
* Built new image with the proposed Dockerfile changes
* Verified the registration of internal DNS entries for ingress and kubevip, jump vm, nfs server and postgres server
* Created the k8s infrastructure in vsphere using the updated internal image with the following command
```
docker run --rm -it \
--group-add root \
--user $(id -u):$(id -g) \
--env-file $HOME/.vsphere_docker_creds.env \
--volume $(pwd):/workspace \
viya4-iac-k8s apply setup install
```
* Queried infrastructure with generated kubeconfig file to verify nodes were successfully created at the indicated k8s version.
* Verified …
=> fix: (IAC-1019) Use apt-get tool in Dockerfile per hadolint recommendation

Dockerfile, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, roles/kubernetes/storage/sig-storage-local-static-provisioner/defaults/main.yaml, variables.tf
* Update the default `kubernetes_version` in the example files to 1.26.7. 
* Updated the default `kubectl` version in the Dockerfile to 1.26.7
* Updated `sig-storage-local-static-provisioner` default version to 2.6.0
*  Versions 2.5.0 and 2.6.0 had no breaking changes or new features that we needed to consider.
* https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/v2.6.0
* https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/v2.5.0
| Scenario | Provider | kubernetes_version | kubectl version | sig-storage-local-static-provisioner | order  | cadence   | notes             |
|----------|----------|--------------------|-----------------|--------------------------------------|--------|-----------|-------------------|
| 1        | …
=> feat: (IAC-1046) Add Support for K8s 1.27

docs/CONFIG-VARS.md, templates/ansible/inventory.tmpl, variables.tf
* Added a validation for the names of the postgres servers, so we did not run into failures when the hostname is assigned.
* Acceptable format: Postgres Server names must follow a valid naming scheme. Name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character
* Automatically convert any postgres server names that have a hyphen inside them (e.g. cds-postgres) to be an underscore inside the group headings within the inventory file. The `postgres_server_name` variable inside the inventory file will still have hyphens.
* Updated doc to reflect these changes, and also synced up Postgres doc with other cloud repos.
| Scenario | Provider | K8s    | Postgres Servers       | Action                | Order  | Cadence   | Notes …
=> feat: (IAC-1089) Valid PG Server Name and Update Doc

roles/kubernetes/node/labels_taints/tasks/labels.yaml, roles/kubernetes/node/labels_taints/tasks/taints.yaml
The current node labelling and tainting code uses the **ansible_hostname** magic variable, which resolves to the node's short hostname. However, when nodes join the cluster, they seem to join based on the output of 'hostname'. On some environments that may resolve to the long hostname. In that case, the node names returned from **kubectl get nodes** will be the FQDN, but the label/taint code will be trying to label based on the short hostname, which will ultimately fail.
The proposed change adjusts the label/taint behavior to select the node using a label selector, which will match on both the short and long hostname.
=> feat: (IAC-1113) Add node labels and taints with a label selector matching on both the short and long hostname

roles/kubernetes/node/labels_taints/tasks/main.yaml
For some of our baremetal clusters, the node names don't adhere to the naming conventions this project appears to expect, so node labelling and tainting doesn't work as desired.
Swapping to using the ansible 'search' test would behave the same as 'find' for simple substring searches, but would also allow for using regular expressions. That gives more options in setting the key values (e.g. '.+' to label all nodes for compute).
=> feat: (IAC-1114) Use the 'search' test rather than find when checking node names for labelling purposes

.github/workflows/linter-analysis.yaml
Update the branch selector for the GitHub workflow to allow it to additionally run against branches that use the [path pattern](https://docs.github.com/en/get-started/using-git/dealing-with-special-characters-in-branch-and-tag-names#about-branch-and-tag-names) (e.g. "fix/IAC-111").
The name of the source branch of this PR uses the path pattern `chore/IAC-1197` and the GitHub workflow was automatically run.
=> chore: (IAC-1197) Update Branch Selector for GitHub Workflow

README.md, docs/CONFIG-VARS.md
Update the SAS Documentation links to `documentation.sas.com`
=> docs: (IAC-1206) Update SAS Documentation URLs

TODO.md, docs/REQUIREMENTS.md, examples/bare-metal/sample-ansible-vars.yaml, examples/bare-metal/sample-inventory, examples/bare-metal/sample-inventory-internal-postgres, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, variables.tf
Remove CR variable from example file and add a TODO file. 
The CR setup ansible roles does not fully setup up a Harbor registry, removing it from doc until it's complete.
=> docs: (IAC-1222) Remove CR Variables from Example Files

examples/vsphere/sample-terraform-minimal.tfvars, outputs.tf
Removes the unused variable `cluster_node_pool_mode` from example file & output
| Scenario | Provider | K8s Version | Notes                                              |
|----------|----------|-------------|----------------------------------------------------|
| 1        | OSS      | 1.26.7      | cluster_node_pool_mode no longer present in output |
=> fix: (IAC-1246) remove unused var `cluster_node_pool_mode` from example & output

Dockerfile, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, examples/bare-metal/sample-ansible-vars.yaml, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, roles/kubernetes/cri/containerd/defaults/main.yaml, roles/kubernetes/toolbox/defaults/main.yaml, roles/kubernetes/toolbox/tasks/main.yaml, variables.tf
Updates the default `kubelet`, `kubectl`, and `kubeadm` versions to 1.27.9. The version of `containerd` was also updated to 1.6.26 to pull in fixes and improvements, this version is still compatible with K8s 1.24+
https://containerd.io/releases/#kubernetes-support
This note will be included in the release notes:
Updated the package repo we source the `kube` packages to now be `pkgs.k8s.io` It's important to note that this new package repo will only distribute binaries for K8s 1.24 and onwards.
From: https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/
> The legacy package repositories (apt.kubernetes.io and yum.kubernetes.io) have been deprecated and frozen starting from September 13, 2023. Using the new package repositories hosted at pkgs.k8s.io is strongly …
=> feat: (IAC-1189) Add Support for K8s 1.28 and Update Default CRI Version

roles/kubernetes/metrics/metrics-server/defaults/main.yaml
Update the default `METRICS_SERVER_CHART_VERSION` default to 3.11.0 to pull in fixes and improvements. This version is compatible with K8s 1.19+
https://github.com/kubernetes-sigs/metrics-server?tab=readme-ov-file#compatibility-matrix
| Scenario | Provider | kubectl version | cluster_version | cluster_cni | cluster_cni_version | cluster_cri | cluster_cri_version | METRICS_SERVER_CHART_VERSION | Order  | Cadence   |
|----------|----------|-----------------|-----------------|-------------|---------------------|-------------|---------------------|------------------------------|--------|-----------|
| 1        | OSS      | 1.27.9          | 1.26.12         | calico      | 3.27.0              | containerd  | 1.6.26              | 3.11.0                       | * | fast:2020 |
| 2        | OSS …
=> feat: (IAC-1187) Update METRICS_SERVER_CHART_VERSION default to 3.11.0

docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, examples/bare-metal/sample-ansible-vars.yaml, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, roles/kubernetes/cni/calico/templates/custom-resources.tmpl, variables.tf
Update the default Calico CNI version to 3.27.0 (`cluster_cni_version` & `kubernetes_cni_version`) to pull in the latest fixes and improvements.
This new version was tested by Tigera to work against K8s 1.24-1.28 so we are bumping the version
https://docs.tigera.io/calico/3.27/getting-started/kubernetes/requirements#kubernetes-requirements
| Scenario | Provider | kubectl version | cluster_version | cluster_cni | cluster_cni_version | cluster_cri | cluster_cri_version | METRICS_SERVER_CHART_VERSION | Order  | Cadence   |
|----------|----------|-----------------|-----------------|-------------|---------------------|-------------|---------------------|------------------------------|--------|-----------|
| 1        | OSS      | 1.27.9          | 1.26.12         | calico      | 3.27.0 …
=> feat: (IAC-1225) Update default Calico CNI Version to 3.27.0

versions.tf
In order to line up with the same Terraform provider/modules versioning standards as the other IAC projects `versions.tf` was updated to use the `~>` notation.
| Scenario | Provider | K8s Version | Order  | Cadence   |
|----------|----------|-------------|--------|-----------|
| 1        | OSS      | v1.28.6     | ****** | fast:2020 |  
| 2        | OSS      | v1.26.13    | ****** | fast:2020 |
=> feat: (IAC-1313) Use the `~>` Notation for Provider Version Constraints

README.md, docs/user/Dependencies.md
Adds more detailed dependencies doc
Closes #15
=> docs: (IAC-1244) Add Detailed Dependencies Documentation 

roles/kubernetes/common/tasks/main.yaml
Only reboot the K8s nodes in `/roles/kubernetes/common/defaults/main.yaml`. Allow other nodes to stay online, allows users who run the IAC code from Jump from having their executions interrupted.
| Scenario | Provider | K8s Version | Order  | Cadence   | Notes                 |
|----------|----------|-------------|--------|-----------|-----------------------|
| 1        | OSS      | v1.28.6     | ****** | fast:2020 | only K8s nodes reboot |
=> feat: (IAC-1269) Update K8s node reboot task to not run on non-k8s node VMs

docs/REQUIREMENTS.md, examples/bare-metal/sample-ansible-vars.yaml, templates/ansible/ansible-vars.yaml.tmpl
A couple of minor doc updates after receiving feedback from users.
=> docs: (IAC-1351) Minor Doc Fixes

Dockerfile, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, docs/user/Dependencies.md, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, roles/kubernetes/control_plane/init/primary/tasks/main.yaml, variables.tf
* Updated the default `kubernetes_version`/`cluster_version` in the example files and doc to 1.28.7
* Updated the default `kubectl` version in the Dockerfile to 1.28.7 (currently the latest)
There was an issue discovered with `kube-vip` and K8s 1.29+. In short kube-vip requires `super-admin.conf` permissions with Kubernetes 1.29 and without it, we run into issues setting up a new cluster with `kubeadm init`. 
`super-admin.conf` was introduced Kubernetes 1.29, and the user within that file is bound to the `system:masters` RBAC group. In previous kubernetes versions the `admin.conf` user was bound to this RBAC group, but now in 1.29 this user is bound to a new group called `kubeadm:cluster-admins` that has `cluster-admin` `ClusterRole` access.
If you take a look at the [1.29 Urgent Upgrade …
=> feat: (IAC-1379) Add Support for K8s 1.29

Dockerfile, docs/REQUIREMENTS.md, roles/kubernetes/common/defaults/main.yaml
Updated the helm version to 3.14.4 to resolve security warnings
| Scenario | Provider | K8s Version | Helm Version | Notes                         |
|----------|----------|-------------|--------------|-------------------------------|
| 1        | OSS      | v1.28.7     | 3.14.4       | apply,setup,install & destroy |
=> feat: (IAC-1438) Update Dependencies to Resolve Security Warnings

docs/REQUIREMENTS.md
Added documentation around time synchronization
=> docs: (IAC-1245) Add Section about Time Synchronization

Dockerfile, docs/REQUIREMENTS.md, roles/kubernetes/common/defaults/main.yaml
=> 3.11.0 - May 17, 2024

Dockerfile, docs/REQUIREMENTS.md
Update binaries
* Terraform 1.7.3 -> 1.8.5
| Scenario | Provider | kubernetes_version | order  | cadence   |
|----------|----------|--------------------|--------|-----------|
| 1        | OSS      | v1.28.7            | * | fast:2020 |
=> feat: (IAC-1475) Update Dependencies

Dockerfile, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, variables.tf
=> 3.12.0 - June 28, 2024

Dockerfile, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, docs/user/Dependencies.md, examples/bare-metal/sample-ansible-vars.yaml, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, variables.tf
* Updated the default `kubernetes_version` in the example files to 1.29.7
* Updated the default `kubectl` version in the Dockerfile to 1.29.7
* Bump calico version to 3.28.0
| Scenario | Provider | Cluster Version | kubectl Version | Order  | Cadence   | Notes                                      |
|----------|----------|-----------------|-----------------|--------|-----------|--------------------------------------------|
| 1        | OSS      | v1.29.7         | v1.29.7         | * | fast:2020 | OOTB                                       |
| 2        | OSS      | v1.30.3         | v1.29.7         | * | fast:2020 | OOTB - overwrite kubectl version in the DO |
| 3        | OSS      | v1.28.11        | v1.29.7         | *| fast:2020 | OOTB                                       |
=> feat: (PSKD-408) (PSKD-513) Support K8s 1.30

Dockerfile, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, docs/user/Dependencies.md, examples/bare-metal/sample-ansible-vars.yaml, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, variables.tf
=> 3.13.0 - August 29, 2024

docs/REQUIREMENTS.md
The storage section of doc/REQUIREMENTS.md needed to include the public default cadence product specific storage requirements.  Instead of duplicating information, we provided a link to the documentation for those requirements.
=> docs: requirements.md points to SAS Viya Platform requirements doc (PSKD-403)

CodingStandards.txt, Dockerfile, docs/REQUIREMENTS.md, docs/user/Dependencies.md, linting-configs/.tflint.hcl, versions.tf
Update 3rd party dependencies. Consumers of the Dockerfile will automatically have these updated dependencies installed. Users who directly run this project locally on their own host will need to update the dependencies themselves.
Update kubectl binary download URL
**Version Update Summary**
* `terraform` 1.8.5 -> 1.9.8
* `helm` 3.14.4 -> 3.16.2
* `kubectl` 1.29.7 -> 1.29.10
| Scenario | K8s version | oss-k8s execution Method | Cadence | Notes
|-|-|-|-|-|
| 1        | 1.29.10        | docker |  n/a | successful cluster creation, no deployment, successful destroy |
| 2        | 1.28.13        | docker |  n/a | successful cluster creation, no deployment, successful destroy |
| 3        | 1.30.4        | docker |  fast:2020 | successful cluster creation, Successful Viya4 deployment and …
=> feat: (PSKD-349) OSS Tool Version Updates

Dockerfile
"chmod" command in Dockerfile moved after the "terraform init" command to allow for overriding the default local backend.
=> fix: permissions set in dockerfile (PSKD-903)

.github/workflows/linter-analysis.yaml, docs/CONFIG-VARS.md, docs/REQUIREMENTS.md, examples/bare-metal/sample-ansible-vars.yaml, examples/vsphere/sample-terraform-dhcp.tfvars, examples/vsphere/sample-terraform-minimal.tfvars, examples/vsphere/sample-terraform-static-ips.tfvars, examples/vsphere/sample-terraform-static-singlestore.tfvars, examples/vsphere/sample-terraform-vi.tfvars, tests/variable_defaults.tftest.hcl, variables.tf
- Update default calico CNI version to use v3.29.0
- Update REQUIREMENTS & CONFIG-VARS docs and sample files to indicate use of v3.29.0
- Created tftest.hcl file to unit test cluster CNI and version default values.
| Scenario | K8s version | oss-k8s execution Method | cluster_cni | cluster_cni_version | vSphere server | Cadence | Notes
|--|-------|-------------|--------|--------------|--------------------------|---------|-------|
| 1  | 1.30.4        | docker | calico | 3.29 | * | fast:2020 | Successful cluster creation using calico v3.29. Successful fast:2020 Viya4 deployment |
=> feat: (PSKD-917) update calico for k8s 1.31 support

Dockerfile, docs/user/Dependencies.md
Bumping several versions to address security vulnerabilities. Docker image users will need to build the image using the latest changes to get the new versions. Consumers who use local tooling will need to update the versions themselves. I've also added a required dependency that was missing from the Dependencies.md doc. 
**Tool updates:**
* `kubectl`: 1.30.8 -> 1.30.10
* `terraform`: 1.9.8 -> 1.10.5
* `helm`: 3.16.2 -> 3.17.1
|Scenario|Method |K8s version|order |cadence|Notes|
|-|-|-|-|-|-|
|1  |terraform 1.10.5 inside docker container |1.30.10      |***   |  stable: 2025.02 |Cluster created successfully with the updated versions indicated in the Changes above. Successful Viya deployment with all pods reaching Running and stable.|
|2   |terraform 1.10.5 using local tooling |1.30.10     …
=> chore: (PSKD-1405) Dependency Version Bumps

README.md
Explicitly state Kubernetes 1.29-1.31 and 1.32 is TBD
=> docs: add k8s support levels (PSKD-1331)

.github/dependabot.yml, .github/workflows/conventional-commits.yml
Update workflows that were targeting staging. They will now target the main branch.
=> chore: update workflows to point to main

README.md
This PR updates to use a specific tagged release of the viya4-iac-k8s module, instead of referencing the main branch.
=> docs: update README to suggest release tags
